title: "Target & Tech: Inside Ad Algorithms"
author: "Dmitry Lastovichek"
description: ""
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header
mathjax: true
google_analytics: G-HB4E5NS2Y5

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  # - {file: "index.html"}
  - {file: "README.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:lastovichekdv@gmail.com"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/lastovichek"}
  - {title: Github, icon: github, url: "https://github.com/necnec"}
  - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: "necnec-github-io"    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed

# Apply this change to _config.yml file
kramdown:
  # parse markdown inside block-level HTML tag
  parse_block_html: true